language: objective-c
osx_image: xcode9
env:
  - DESTINATION="OS=11.0,name=iPhone 7" SCHEME="CreditCardRow" SDK=iphonesimulator

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project CreditCardRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild -project CreditCardRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
